# Generated by Django 4.0.4 on 2022-06-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_firstname_customer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mileage', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_complete', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.customer')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Waiting Pickup', 'Waiting Pickup'), ('Complete', 'Complete')], max_length=100)),
                ('tune', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('totalCost', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('passInspection', models.BooleanField(default=False)),
                ('truckInShop', models.DateField()),
                ('truckOutShop', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.order')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.truck')),
            ],
        ),
    ]
