# Generated by Django 4.0.4 on 2022-06-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee_truck_order_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='phone',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.customer'),
        ),
    ]
