# Generated by Django 4.0.4 on 2022-06-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_truck_phone_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='owner',
            new_name='customer',
        ),
    ]
