# Generated by Django 4.0.4 on 2022-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_owner_truck_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateField(null=True),
        ),
    ]
