# Generated by Django 4.0.4 on 2022-06-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_order_date_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
