# Generated by Django 4.0.4 on 2022-06-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_order_date_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='truck',
        ),
    ]
