# Generated by Django 4.0.4 on 2022-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_maintenance_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='totalCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='truckInShop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='truckOutShop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
